<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Place;
use Illuminate\Database\Seeder;

class PlaceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::pluck('id', 'nama')->toArray();

        Place::insert([
            [
                'category_id' => $categories['Alam'],
                'nama' => 'Bukit Kapur Jaddih',
                'alamat' => 'Jakan, Parseh, Kec. Socah, Kabupaten Bangkalan, Jawa Timur 69161',
                'gmaps_link' => 'https://maps.app.goo.gl/61DnuVv9f4HQbhtz7',
                'deskripsi' => '<div>Bukit Jaddih terletak di Desa Jaddih, Kecamatan Socah, Kebupaten Bangkalan, Madura, Jawa Timur. Bukit Jaddih merupakan tambang kapur yang diubah menjadi tempat wisata dan layak untuk dikunjungi. Tempat ini dapat menjadi salah satu agenda wisata saat berada di Madura, terutama penggemar foto.<br><br>Bukit Jaddih memiliki pemandangan yang luar biasa. Bukit tambang kapur ini digali dan dibuka untuk menghadirkan pemandangan buatan yang indah. Uniknya, pertambangan ditempat ini masih berlangsung, sehingga ada pamandangan truk dan alat berat yang lalu lalang. Bukit Jaddih memiliki danau buatan dengan air berwarna hijau, wisatawan akan mendapatkan spot yang indah di tempat ini.<br><br>Danau dikelilingi bukit kapur yang terpahat. Tempat ini semakin memukau dengan kombinasi langit yang cerah. Untuk menikmati pemandangan sekitar danau, tersedia rakit yang disewakan kepada para wisatawan. Wisatawan tidak perlu khawatir dengan kondisi danau, kedalaman danau hanya sekitar 70 sentimeter (cm). Setelah menikmati keliling menggunakan rakit, perjalanan dapat dilanjutkan menuju rongga-rongga bukit. Banyak spot foto di wilayah ini sebagai kenang-kenangan. Ada juga kolam renang yang tersedia untuk bermain-main. Air kolam renang terasa segar di tengah perbukitan kapur yang panas. Bagi wisatawan yang ingin berbelanja tersedia toko aksesoris Goa Pote.</div>',
                'image' => 'wisata-images/rF1OxHxywqDD1LsP9QromFYBPc19bMXxPdQjJX3w.jpg',
                'harga_tiket' => 10000,
                'jam_buka' => '07:00',
                'jam_tutup' => '16:00',
                'jumlah_tiket_weekday' => 100,
                'jumlah_tiket_weekend' => 300,
            ],
            [
                'category_id' => $categories['Sejarah'],
                'nama' => 'Mercusuar “Dutch East Indies” Bangkalan',
                'alamat' => 'Jalan Sembilangan, Socah, Slempit, Pernajuh, Kec. Bangkalan, Kabupaten Bangkalan, Jawa Timur 69161',
                'gmaps_link' => 'https://maps.app.goo.gl/xPSxU6f2NZRUrfcG9',
                'deskripsi' => '<div><strong>Mercusuar Sembilangan</strong> atau <strong>Mercusuar Ujung Slempit</strong> adalah sebuah mercusuar yang terletak di Pulau Madura, Jawa Timur. Mercusuar tersebut didirikan pada 1879. Mercusuar tersebut memiliki ketinggian 78 meter dan lingkar 5,3 meter. Mercusuar tersebut berbetnuk menara besi bercat putih dengan lentera dan galeri. Mercusuar tersebut terletak di lepas pantai ujung paling barat Madura. Mercusuar tersebut adalah penerangan pendaratan dan penerangan untuk memandu kapal-kapal yang melewati selat antara Madura dan Jawa untuk menuju ke pelabuhan Surabaya.</div>',
                'image' => 'wisata-images/1lQUAluZ1An96DSXEv03YJkrW9bNMHFQ1zPZlmul.png',
                'harga_tiket' => 5000,
                'jam_buka' => '08:00',
                'jam_tutup' => '16:00',
                'jumlah_tiket_weekday' => 100,
                'jumlah_tiket_weekend' => 200,
            ],
            [
                'category_id' => $categories['Taman'],
                'nama' => 'Taman Paseban Bangkalan',
                'alamat' => 'Jalan Veteran, Kraton, Bangkalan, Demangan Barat, Demangan, Kec. Bangkalan, Kabupaten Bangkalan, Jawa Timur 69115',
                'gmaps_link' => 'https://maps.app.goo.gl/D8fAq394X8U3mLfA7',
                'deskripsi' => '<div>Taman Paseban di Kota Bangkalan adalah salah satu ikon wisata kota yang berlokasi strategis di tengah kota, berhadapan langsung dengan Masjid Agung Bangkalan. Taman ini sering menjadi tujuan utama bagi keluarga untuk mengajak anak-anak bermain dan bersantai. Dengan suasana yang hijau dan adem, Taman Paseban menawarkan area yang nyaman untuk berkumpul dan menikmati waktu bersama .<br><br></div><div>Taman ini juga dilengkapi dengan fasilitas pendopo, kantin, dan toilet yang memudahkan pengunjung untuk menikmati waktu mereka dengan lebih nyaman . Renovasi yang dilakukan pada Taman Paseban telah memperluas dan meningkatkan fasilitas yang ada, menjadikannya lebih menarik dan fungsional untuk memenuhi kebutuhan masyarakat Bangkalan .<br><br></div><div>Taman Paseban tidak hanya berfungsi sebagai tempat rekreasi, tetapi juga memiliki nilai sejarah dan budaya yang penting bagi warga setempat. Keberadaannya di pusat kota membuatnya mudah diakses dan sering menjadi tempat untuk berbagai kegiatan sosial dan budaya .</div>',
                'image' => 'wisata-images/BCsiNtMEeqVrl6CgNj8HuMj9y9NpYYWYQ2TflMpM.jpg',
                'harga_tiket' => 3000,
                'jam_buka' => '06:00',
                'jam_tutup' => '17:00',
                'jumlah_tiket_weekday' => 200,
                'jumlah_tiket_weekend' => 500,
            ],
            [
                'category_id' => $categories['Religi'],
                'nama' => 'Makam Aer Mata Ibu',
                'alamat' => 'Makam Air Mata, Buduran, Kec. Arosbaya, Kabupaten Bangkalan, Jawa Timur 69151',
                'gmaps_link' => 'https://maps.app.goo.gl/TbdAeWpiz6ZQYDdc8',
                'deskripsi' => '<div><strong>Makam Aer Mata Ibu</strong> adalah sebuah kompleks pemakaman bangsawan Madura yang terletak di Desa Buduran, Kecamatan Arosbaya, Kabupaten Bangkalan, di Pulau Madura, diperkirakan dibangun sejak abad ke-15. Di kompleks ini dimakamkan para bangsawan dari Wangsa Cakraningrat, beserta kerabat dan abdi dalem istana lainnya. Kompleks ini dibangun di atas perbukitan kapur, dengan ketinggian + 30 m di atas permukaan laut.</div><div><br>Menurut cerita rakyat, nama kompleks pemakaman ini diambil dari kisah Ratu Ibu (Syarifah Ambami, isteri Adipati Cakraningrat I), yang menangis di pertapaannya.</div>',
                'image' => 'wisata-images/rISX1sXWfDLQKxt0apRyytEeUerGaQbGHQZU84U9.jpg',
                'harga_tiket' => 5000,
                'jam_buka' => '07:00',
                'jam_tutup' => '16:00',
                'jumlah_tiket_weekday' => 150,
                'jumlah_tiket_weekend' => 200,
            ],
            [
                'category_id' => $categories['Pantai'],
                'nama' => 'Pantai Pasir Putih Tlangoh',
                'alamat' => 'Temanah, Tlangoh, Kec. Tj. Bumi, Kabupaten Bangkalan, Jawa Timur 69156',
                'gmaps_link' => 'https://maps.app.goo.gl/jhAudW71zgqNiz1X6',
                'deskripsi' => '<div>Salah satu daya tarik wisata di Pulau Madura adalah pantainya yang indah dan memesona. Salah satunya adalah Pantai Tlangoh yang terletak di Desa Tlangoh, Kecamatan Tanjungbumi, Kabupaten Bangkalan, Jawa Timur.<br><br></div><div>Pantai ini menawarkan panorama alam yang menakjubkan dengan hamparan pasir putih, air laut yang biru, dan angin sepoi-sepoi yang menyegarkan.</div><div><br>Pantai Tlangoh merupakan salah satu wisata pantai yang cukup populer di Bangkalan Madura. Banyak wisatawan yang datang ke pantai ini untuk menikmati keindahan dan keseruan pantai.<br><br></div><div>Di pantai ini, pengunjung bisa bermain pasir, berenang, berfoto, atau sekadar bersantai di tepi pantai.<br><br></div><div>Pantai ini juga memiliki beberapa spot foto yang menarik, seperti ayunan, jembatan kayu, dan gazebo.<br><br></div><div>Untuk menuju Pantai Tlangoh, pengunjung bisa menggunakan kendaraan pribadi atau umum. Jarak pantai ini sekitar 40 km dari kota Bangkalan.</div>',
                'image' => 'wisata-images/Fu8pBkbqxz8V58Qul7mxTGew6WvgYbAHUl1OpDwt.jpg',
                'harga_tiket' => 15000,
                'jam_buka' => '07:00',
                'jam_tutup' => '16:00',
                'jumlah_tiket_weekday' => 100,
                'jumlah_tiket_weekend' => 300,
            ],
            [
                'category_id' => $categories['Pantai'],
                'nama' => 'Pantai Siring Kemuning',
                'alamat' => 'Macajah, Kec. Tj. Bumi, Kabupaten Bangkalan, Jawa Timur 69156',
                'gmaps_link' => 'https://maps.app.goo.gl/qsRUUmmMZ4AFqQvA8',
                'deskripsi' => '<div>Pantai Siring Kemuning merupakan tempat wisata murah yang dapat di kunjungi saat berada di Kabupaten Bangkalan. Pantai ini memiliki pasir yang agak berwarna kuning begitu pula dengan ombaknya.<br><br></div><div>Pantai Siring Kemuning berjarak sekitar 40 km dari pusat kota Bangkalan Madura. Jarak tempuh kurang lebih 1 jam perjalanan dari pusat kota.Tepatnya berada di Desa Macajah, Kecamatan Tanjungbumi, Kabupaten Bangkalan, Jawa Timur.<br><br>Banyak aktifitas yang dapat anda lakukan untuk sekedar menghilangkan kepenatan bekerja atau menghabiskan waktu berwisata bersama teman dan keluarga tercinta. Anda dapat bermandi-mandi, bermain pasir dan bermain voli bersama teman- teman.<br><br></div><div>Saat berkunjung ke pantai Siring Kemuning sebaiknya datang di pagi hari atau di saat sore karena di waktu siang, sinar matahari begitu terik bisa membakar kulit anda.<br><br></div><div>Jangan lupa pula untuk mengabadikan momen berwisata anda di pantai Siring Kemuning, banyak spot foto anti mainstream yang dapat menambah koleksi foto menarik anda.</div>',
                'image' => 'wisata-images/lO1evqiPYeDZkINM052t3neiOmigUfcGB7yWQSwh.jpg',
                'harga_tiket' => 15000,
                'jam_buka' => '08:00',
                'jam_tutup' => '16:00',
                'jumlah_tiket_weekday' => 100,
                'jumlah_tiket_weekend' => 250,
            ],
            [
                'category_id' => $categories['Kolam Renang'],
                'nama' => 'Kolam Renang Tretan',
                'alamat' => 'Area Sawah, Mlajah, Kec. Bangkalan, Kabupaten Bangkalan, Jawa Timur 69116',
                'gmaps_link' => 'https://maps.app.goo.gl/jPLNJdjN5jd8t3rs9',
                'deskripsi' => '<div>Kolam Renang Tretan adalah sebuah obyek wisata air yang mempunyai lokasi di Kabupaten Bangkalan, Madura. Jika anda sedang berkunjung ke pulau garam ini bersama anak-anak atau keponakan yang masihh kecil, anda bisa mengajak mereka untuk bersenang-senang bermain air di Kolam Renang Tretan.&nbsp;<br><br>Untuk bangunan dari kolam renangnya sendiri, di sini berbentuk bangunan tinggi yang mempunyai dua tingkat lantai. Untuk lantai pertama atau lantai dasar digunakan sebagai tempat kolam renangnya, lalu untuk lantai kedua digunakan sebagai tempat kantin-kantin yang berkonsep cafe yang menjual berbagai makanan dan minuman. Dari tempat ini anda bisa manfaatkan untuk melihat-lihat pemandangan dari atas sambil menikmati snack.<br><br></div><div>Kolam renang yang disediakan di sana memang tidak terlalu besar namun sangat cukup untuk menampung pengunjung yang banyak datang pada saat masa liburan sekolah atau akhir pekan. Ada dua kolam renang yang bisa anda pakai, yang pertama diperuntukan bagi anak-anak atau orang yang tidak bisa berenang dengan kedalaman hanya satu meter saja. Untuk kolam yang kedua digunakan bagi orang dewasa dengan kedalamaannya yang mencapai 1,5 meter.<br><br></div><div>Untuk menambah keseruan saat bermain atau berendam di Kolam Renang Tretan, pihak pengelola juga telah menyediakan beberapa seluncuran yang terdapat di pinggir kolam yang bisa digunakan untuk anak-anak maupun orang dewasa. Dengan biaya yang tidak mahal, anda sudahh bisa mengajak keluarga beserta anak-anak anda untuk menikmati serunya bermain air di pulau Madura. Anda juga bisa memanfaatkan kolam renang di sana untuk mengajari anak-anak anda berenang dan memperkenalkan mereka supaya mereka tidak takut dengan air.</div>',
                'image' => 'wisata-images/1o1hy6U7QTYriGNpaxdVVomsIbqVtJ3ytReXNdRL.jpg',
                'harga_tiket' => 8000,
                'jam_buka' => '07:00',
                'jam_tutup' => '16:00',
                'jumlah_tiket_weekday' => 50,
                'jumlah_tiket_weekend' => 100,
            ],
            [
                'category_id' => $categories['Taman'],
                'nama' => 'Taman Rekreasi Kota Bangkalan',
                'alamat' => 'Mlajah, Kec. Bangkalan, Kabupaten Bangkalan, Jawa Timur 69116',
                'gmaps_link' => 'https://maps.app.goo.gl/qcheBC33xSo2grsy8',
                'deskripsi' => '<div>Salah satu obyek wisata minat khusus tengah kota yang dikelola langsung oleh Pemerintah Kabupaten Bangkalan. Taman tengah kota yang di penuhi dengan bermacam – macam wahana bermain anak - anak, kolam renang dan danau buatan yang di desain khusus bagi anda yang hobi memancing atau sekedar ingin bermain perahu mengelilingi danau.</div>',
                'image' => 'wisata-images/tRwzwAXuW3OrJN3hcALu4O5MQOUETCXeJCXUHIjW.jpg',
                'harga_tiket' => 3000,
                'jam_buka' => '08:00',
                'jam_tutup' => '17:00',
                'jumlah_tiket_weekday' => 100,
                'jumlah_tiket_weekend' => 250,
            ],
            [
                'category_id' => $categories['Pantai'],
                'nama' => 'Pantai Martajasah',
                'alamat' => 'Jl. Raya Kramat, Area Sawah, Mertajasah, Kec. Bangkalan, Kabupaten Bangkalan, Jawa Timur',
                'gmaps_link' => 'https://maps.app.goo.gl/zthJoLvsxTzKbNfq5',
                'deskripsi' => '<div>Pantai Martajasah, yang terletak di Desa Martajasah, Kecamatan Kota Bangkalan, adalah destinasi wisata baru yang mulai menarik perhatian banyak wisatawan meskipun belum resmi dibuka. Pantai ini hanya berjarak sekitar 10 menit dari pusat kota Bangkalan, menjadikannya mudah diakses bagi penduduk lokal maupun wisatawan luar daerah.</div><div><br>Pantai Martajasah menawarkan pemandangan laut yang indah dengan biaya masuk yang sangat terjangkau, yaitu hanya Rp 2.000 untuk parkir roda dua. Tempat ini terkenal dengan pesona matahari terbenamnya yang memukau dan deretan hutan mangrove yang memberikan pengalaman wisata alam yang berbeda dan menarik.<br><br></div><div>Keindahan alam yang ditawarkan Pantai Martajasah membuatnya menjadi pilihan yang cocok untuk tempat berlibur, terutama saat momen libur panjang seperti Lebaran. Keberadaan hutan mangrove juga menambah daya tarik tersendiri, memberikan pengunjung kesempatan untuk menikmati suasana pantai sekaligus keindahan alam liar.</div><div><br>Dengan pemandangan yang menakjubkan dan fasilitas yang cukup memadai, Pantai Martajasah siap menjadi salah satu destinasi wisata favorit di Bangkalan dan sekitarnya.</div>',
                'image' => 'wisata-images/wYkgWeFbKKS5R8LR9UVBHSQprH0Gk6tWUfjBEfit.webp',
                'harga_tiket' => 3000,
                'jam_buka' => '08:00',
                'jam_tutup' => '19:00',
                'jumlah_tiket_weekday' => 100,
                'jumlah_tiket_weekend' => 150,
            ],
            [
                'category_id' => $categories['Religi'],
                'nama' => 'Makam Syaikhona Kholil',
                'alamat' => 'Jl. Mertajasah, Tajasah, Mertajasah, Kec. Bangkalan, Kabupaten Bangkalan, Jawa Timur 69119',
                'gmaps_link' => 'https://maps.app.goo.gl/j6dMaV1EBSix5j6y9',
                'deskripsi' => '<div>Makam Syaikhona Kholil Bangkalan merupakan salah satu objek wisata religi di Madura. Lokasi Makam Syaikhona Kholil Bangkalan terletak di Desa Martajasah, Kabupaten Bangkalan, Madura, Jawa Timur. Syekh Muhammad Kholil bin Abdul Latif sering dikenal dengan nama Syaikhona Kholil atau Syekh Kholil. Syaikhona Kholil adalah guru ulama Indonesia dan juga Bapak Pesantren Indonesia. Murid-muridnya menyebar dan mendirikan pondok pesantren di berbagai tempat. Salah satu murid Syaikhona Kholil adalah KH Hasyim Asy\'ari, pendiri Nahdlatul Ulama (NU).<br><br>Makam Syaikhona Kholil Bangkalan menjadi salah satu destinasi wisata religi di Madura, yang tidak pernah sepi pengunjung. Banyaknya peziarah yang berkunjung ke makam tersebut tidak telepas dari sosok Syaikhona Kholil sebagai ulama besar. Selain makam Syaikhona Kholil juga terdapat makam ayahnya yang bernama Abdul Latif. Ada juga makam anggota keraton dan makam waliyulloh yang disampingnya terdapat sumur tua. Masyarakat setempat mempercayai bahwa jika melempar uang koin ke dalam sumur akan mendapatkan rezeki besar, sedangkan jika meminum airnya akan mendapatkan kesehatan yang panjang.<br><br>Tepat di lokasi pemakaman terdapat masjid yang dibangun sebagai bentuk penghomatan kepada ulama dan diberi nama Masjid Syaikhona Muhammad Kholil. Fasilitas yang ditawarkan makam tersebut, seperti kamar mandi umum, masjid untuk beribadah, dan beberapa bangku untuk beristirahat atau giliran menunggu berziarah. Di bagian luar makam terdapat banyak tempat makan dan beberapa toko souvenir khas Madura.</div>',
                'image' => 'wisata-images/mkS4GDEibl7M1nvWumgZAAQ66wqrlM10U70kMd7o.jpg',
                'harga_tiket' => 5000,
                'jam_buka' => '09:00',
                'jam_tutup' => '17:00',
                'jumlah_tiket_weekday' => 300,
                'jumlah_tiket_weekend' => 500,
            ],
            [
                'category_id' => $categories['Religi'],
                'nama' => 'Masjid Agung Bangkalan',
                'alamat' => 'Jalan Sultan R Jl. Sultan Abd. Kadirun No.5, Demangan Barat, Demangan, Kec. Bangkalan, Kabupaten Bangkalan, Jawa Timur 69115',
                'gmaps_link' => 'https://maps.app.goo.gl/TrucXVhjyqS138Ci7',
                'deskripsi' => '<div>Masjid Agung Bangkalan adalah salah satu masjid bersejarah dan ikonik di Bangkalan, Madura. Didirikan pada tahun 1819 oleh Sultan Abdul Kadirun, masjid ini telah menjadi pusat kegiatan keagamaan dan sosial bagi masyarakat sekitar selama lebih dari dua abad.<br><br></div><div>Masjid ini terletak di Jalan KH. Moh. Kholil dan dikenal karena arsitektur tradisionalnya yang indah, memadukan elemen-elemen khas budaya Madura dengan seni Islam. Dengan bangunan yang megah dan halaman yang luas, Masjid Agung Bangkalan tidak hanya berfungsi sebagai tempat ibadah, tetapi juga sebagai pusat kegiatan masyarakat.<br><br></div><div>Sebagai salah satu masjid tertua di Madura, Masjid Agung Bangkalan menyimpan banyak nilai sejarah. Masjid ini merupakan bukti kejayaan dan pengaruh kerajaan Islam di wilayah tersebut. Berbagai renovasi dan pemeliharaan telah dilakukan untuk menjaga keaslian dan kemegahan bangunan ini, sehingga tetap menjadi daya tarik wisata religi yang populer di Madura.</div><div><br>Pengunjung yang datang ke Masjid Agung Bangkalan tidak hanya dapat menikmati keindahan arsitektur masjid, tetapi juga merasakan suasana religius dan damai yang terpancar dari tempat ini. Masjid ini menjadi saksi bisu perjalanan panjang sejarah Islam di Bangkalan dan tetap menjadi salah satu simbol kebanggaan masyarakat setempat.</div>',
                'image' => 'wisata-images/EwHdDWGK5z3N9edOda977sbmO2EQx1JrxrZ01OAl.jpg',
                'harga_tiket' => 3000,
                'jam_buka' => '06:00',
                'jam_tutup' => '19:00',
                'jumlah_tiket_weekday' => 200,
                'jumlah_tiket_weekend' => 300,
            ],
            [
                'category_id' => $categories['Pantai'],
                'nama' => 'Pantai Rongkang',
                'alamat' => 'Kejawan, Kwanyar Bar., Kec. Kwanyar, Kabupaten Bangkalan, Jawa Timur 69163',
                'gmaps_link' => 'https://maps.app.goo.gl/a1SukJkiEwVu1YLLA',
                'deskripsi' => '<div>Pantai Rongkang terletak di Desa Kwanyar Barat, Kecamatan Kwanyar, Kabupaten Bangkalan, Madura, sekitar 35 km di selatan kota Bangkalan. Pantai ini berada di sebelah timur Jembatan Suramadu, menjadikannya lokasi yang mudah diakses dan menarik bagi wisatawan.<br><br></div><div>Pantai Rongkang terkenal dengan keindahan alamnya yang menakjubkan. Pantai ini memiliki formasi batu karang yang unik dan pemandangan laut yang mempesona. Pengunjung dapat menikmati pemandangan matahari terbenam yang indah dan suasana pantai yang tenang. Selain itu, pantai ini juga menjadi tempat yang ideal untuk menikmati pemandangan Jembatan Suramadu dari kejauhan.<br><br></div><div>Meskipun memiliki potensi wisata yang besar, pengembangan Pantai Rongkang sebagai destinasi wisata utama belum sepenuhnya terealisasi. Beberapa upaya pengembangan telah dilakukan, tetapi perhatian lebih lanjut diperlukan untuk memaksimalkan potensi pantai ini tanpa merusak keasliannya.<br><br></div><div>Pantai Rongkang adalah pilihan yang tepat bagi wisatawan yang mencari tempat yang tenang dan alami untuk bersantai, menikmati pemandangan laut, dan mengeksplorasi formasi batu karang yang menakjubkan.</div>',
                'image' => 'wisata-images/kgZdN6W8NPYkcQnY3pNvHst510VHSfoMgglLfsSl.jpg',
                'harga_tiket' => 15000,
                'jam_buka' => '08:00',
                'jam_tutup' => '17:00',
                'jumlah_tiket_weekday' => 50,
                'jumlah_tiket_weekend' => 1000,
            ],
            [
                'category_id' => $categories['Alam'],
                'nama' => 'Bukit Lampion Beramah',
                'alamat' => 'Tengginah, Daleman, Kec. Galis, Kabupaten Bangkalan, Jawa Timur 69173',
                'gmaps_link' => 'https://maps.app.goo.gl/1avXTDu4Wgc4uScH7',
                'deskripsi' => '<div>Bukit Lampion Beramah (BLB) adalah salah satu destinasi wisata alam yang menarik di Bangkalan, Madura. Terletak di Desa Daleman, Kecamatan Galis, tempat ini menawarkan pemandangan alam yang memukau dan berbagai spot foto yang Instagramable. Bukit ini terkenal dengan keindahan pemandangan alam terbuka yang memanjakan mata para pengunjung.<br><br></div><div>Bukit Lampion Beramah memiliki berbagai fasilitas yang menarik, termasuk spot-spot foto yang didesain dengan lampion-lampion yang indah. Tempat ini sangat cocok untuk wisatawan yang ingin menikmati keindahan alam sambil berfoto ria dengan latar belakang yang menakjubkan. Selain itu, lokasi ini juga menjadi tempat yang populer untuk menikmati pemandangan Kota Bangkalan dari ketinggian.<br><br></div><div>Tempat wisata ini telah berhasil menarik perhatian banyak pengunjung, baik dari dalam maupun luar Bangkalan, karena daya tarik alamnya yang luar biasa dan suasana yang menenangkan. Bukit Lampion Beramah menjadi salah satu rekomendasi terbaik untuk menghabiskan waktu liburan akhir pekan bersama keluarga dan teman.</div>',
                'image' => 'wisata-images/Cwb5rrnFltGSovkKQCV3C4ZhIReJ9J4ceUxjBAn5.jpg',
                'harga_tiket' => 10000,
                'jam_buka' => '07:00',
                'jam_tutup' => '16:00',
                'jumlah_tiket_weekday' => 70,
                'jumlah_tiket_weekend' => 100,
            ],
            [
                'category_id' => $categories['Sejarah'],
                'nama' => 'Museum Cakraningrat',
                'alamat' => 'Jl. Soekarno Hatta No.35, Wr 08, Mlajah, Kec. Bangkalan, Kabupaten Bangkalan, Jawa Timur 69116',
                'gmaps_link' => 'https://maps.app.goo.gl/FYCEDsp8uUEjzXF98',
                'deskripsi' => '<div><strong>Museum Cakraningrat</strong> adalah museum yang terletak di Jalan Soekarno Hatta No. 39 A, Kabupaten Bangkalan, Pulau Madura. Museum ini didirikan pada tahun 2007 oleh Gubernur Jawa Timur, Bapak Imam Utomo. Museum ini diresmikan pada tanggal 13 Maret 2008. Nama Museum Cakraningrat digunakan untuk mengenang dan menghormati jasa dan kebesaran Pangeran Cakraningrat. Pada awal berdiri, benda-benda koleksi museum ini berpindah-pindah tempat dan berganti nama tempatnya. Pada tanggal 13 Maret 2008 Pemerintah Kabupaten Bangkalan mulai antusias memperhatikan peninggalan-peninggalan bersejarah yang ada di Kabupaten Bangkalan sehingga dibangun bangunan gedung museum baru dengan nama Museum Cakraningrat.<br><br>Objek-objek yang dapat ditemui dalam museum ini diantaranya, kain batik Madura, Peralatan batik, Alat membatik ukiran, Menangan, Paeduwan, Bokor, Pengel, Cucuk Sisir, Kereta Kuda, Miniatur Perahu, Kekeyan, Ginggung, Srone, Kleles, Kentongan, dan Gamelan Ratna Dumila.</div>',
                'image' => 'wisata-images/tzFDA8NIccLqrTEXyQ34p6Ud9966wF7A9yc266l9.jpg',
                'harga_tiket' => 5000,
                'jam_buka' => '08:00',
                'jam_tutup' => '16:00',
                'jumlah_tiket_weekday' => 70,
                'jumlah_tiket_weekend' => 100,
            ],
            [
                'category_id' => $categories['Religi'],
                'nama' => 'Perahu Sarimuna',
                'alamat' => 'Jl. Pelabuhan Telagabiru, Telaga Biru, Kec. Tj. Bumi, Kabupaten Bangkalan, Jawa Timur 69156',
                'gmaps_link' => 'https://maps.app.goo.gl/QgtFWixfm7kranQW6',
                'deskripsi' => '<div>Perahu Sarimuna adalah salah satu peninggalan bersejarah dari Syaikhona Kholil Bangkalan, seorang ulama besar yang dihormati di Nusantara. Terletak di Desa Telaga Biru, Kecamatan Tanjung Bumi, Kabupaten Bangkalan, perahu ini menjadi saksi bisu dari masa kejayaan Syaikhona Kholil. Jaraknya sekitar satu jam perjalanan dari pusat kota Bangkalan.<br><br></div><div>Perahu Sarimuna dikenal karena keajaiban dan nilai sejarahnya. Meski usianya sudah sangat tua, perahu ini masih terawat dengan baik. Bentuknya yang unik dan penuh dengan cerita sejarah menjadikannya daya tarik utama bagi wisatawan yang ingin mengenal lebih dalam tentang warisan Syaikhona Kholil. Perahu ini juga diyakini memiliki beberapa keajaiban, seperti tidak mudah rusak meski telah berusia ratusan tahun.</div><div><br>Pengunjung yang datang ke Perahu Sarimuna biasanya tertarik dengan cerita-cerita mistis dan historis yang melingkupinya. Banyak yang percaya bahwa perahu ini memiliki kekuatan spiritual yang kuat, mengingat sosok Syaikhona Kholil yang sangat dihormati dan dianggap sebagai guru besar para ulama di Indonesia.</div>',
                'image' => 'wisata-images/2TQrnAtVX0Evl2Ri7URECtsGKOHRPjwMoRQSqYt4.jpg',
                'harga_tiket' => 10000,
                'jam_buka' => '08:00',
                'jam_tutup' => '16:00',
                'jumlah_tiket_weekday' => 100,
                'jumlah_tiket_weekend' => 200,
            ],
        ]);
    }
}
